### PR TITLE
DTD violations for frontmatter and poly/power

### PR DESCRIPTION
**Pull request by Alex-Jordan**
Here, all I did was temporarily comment out all chapters except power functions and polynomials, and then use `make check` to see what DTD violations there were, and then fix them. Some DTD violations remain, but they are ones that I know are OK.

Thought you might like to review the diff here to see them. I'm going to move on to a more detailed review line by line. May or may not post another commit later today.

### CODE REVIEW

**Review by nick-chura — APPROVED** [review]

**Comment by nick-chura** [comment]
I see several `<hyphen />`s changed to just keyboard hyphens, "-". I understand the change when they're inside of a `<term>`, but why the change outside?

**Comment by nick-chura** [comment]
Oops. I see that I should have just read and let this sit, in case you were going to post another commit.

**Comment by Alex-Jordan** [comment]
Re `hyphen`, see here: https://groups.google.com/forum/#!forum/mathbook-xml-support

Basically I didn't think that was a thing. It registered as a DTD violation.

**Comment by nick-chura** [comment]
I was just over there, saw your post, and came back here to tell you I saw it. I actually didn't know if it was a thing or not, but knowing <ndash /> and <mdash /> are defined, I tried it out and it seemed to do what I expected. I'll hold off on those until Rob gets back to you.

**Comment by nick-chura** [comment]
... but knowing `<mdash />` and `<ndash />` are defined...

**Pull request merged**
