### PR TITLE
finished gist and activity for log chapter

### PR DESCRIPTION
**Pull request by beg4rain**

### CODE REVIEW

**Comment by nick-chura** [comment]
Conflicts!

**Comment by nick-chura** [comment]
Line 819:  For any base, the bigger the result we want to get, the bigger the exponent needs to be. So the logarithm should be an increasing function.

In other places you mention the base being greater than zero, but here you would have to say greater than one. In getting students to imagine what a log graph looks like, maybe it would be helpful to use a particular base as an example.

**Comment by nick-chura** [comment]
Line 966:  The y-axis is a vertical asymptote. It represents a boundary the graph cannot cross.

I imagine someone taking issue with the notion that a graph can't touch a vertical asymptote. Might it be worth changing to "... represents the outputs increasing toward infinity as x --> 0 from the right" (or something similar)?

**Comment by beg4rain** [comment]
Can a graph touch a vertical asymptote??

**Pull request merged**
